insert into exercises (name, muscle_group, equipment) values
  ('Supino reto', 'Peito', 'Barra'),
  ('Supino inclinado com halteres', 'Peito', 'Halteres'),
  ('Crucifixo na polia', 'Peito', 'Cabo'),
  ('Crossover', 'Peito', 'Cabo'),
  ('Flexão de braço', 'Peito', 'Peso corporal'),
  ('Puxada frontal', 'Costas', 'Cabo'),
  ('Remada curvada', 'Costas', 'Barra'),
  ('Remada unilateral', 'Costas', 'Halteres'),
  ('Barra fixa', 'Costas', 'Peso corporal'),
  ('Levantamento terra', 'Costas', 'Barra'),
  ('Desenvolvimento militar', 'Ombros', 'Barra'),
  ('Elevação lateral', 'Ombros', 'Halteres'),
  ('Elevação frontal', 'Ombros', 'Halteres'),
  ('Remada alta', 'Ombros', 'Cabo'),
  ('Crucifixo inverso', 'Ombros', 'Halteres'),
  ('Rosca direta', 'Bíceps', 'Barra'),
  ('Rosca alternada', 'Bíceps', 'Halteres'),
  ('Rosca scott', 'Bíceps', 'Barra W'),
  ('Rosca martelo', 'Bíceps', 'Halteres'),
  ('Tríceps corda', 'Tríceps', 'Cabo'),
  ('Tríceps testa', 'Tríceps', 'Barra W'),
  ('Mergulho no banco', 'Tríceps', 'Peso corporal'),
  ('Tríceps francês', 'Tríceps', 'Halteres'),
  ('Agachamento livre', 'Quadríceps', 'Barra'),
  ('Leg press', 'Quadríceps', 'Máquina'),
  ('Cadeira extensora', 'Quadríceps', 'Máquina'),
  ('Afundo', 'Quadríceps', 'Halteres'),
  ('Stiff', 'Posterior', 'Barra'),
  ('Mesa flexora', 'Posterior', 'Máquina'),
  ('Cadeira flexora', 'Posterior', 'Máquina'),
  ('Elevação pélvica', 'Glúteos', 'Barra'),
  ('Cadeira abdutora', 'Glúteos', 'Máquina'),
  ('Coice na polia', 'Glúteos', 'Cabo'),
  ('Panturrilha em pé', 'Panturrilha', 'Máquina'),
  ('Panturrilha sentado', 'Panturrilha', 'Máquina'),
  ('Abdominal supra', 'Abdômen', 'Peso corporal'),
  ('Prancha', 'Abdômen', 'Peso corporal'),
  ('Elevação de pernas', 'Abdômen', 'Peso corporal');
